<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <NuGetLockFilePath>packages.$(Configuration).lock.json</NuGetLockFilePath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Game.Core/Game.Core.csproj" />
  </ItemGroup>
</Project>
